name = "CoastalCurrents"
uuid = "12750a1a-8500-4ab4-99d8-5bd0a9331725"
authors = ["Alexander Barth <barth.alexander@gmail.com>"]
version = "0.1.0"

[deps]
DIVAnd = "efc8151c-67de-5a8f-9a35-d8f54746ae9d"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
PhysOcean = "3725be50-bbbd-5592-92c3-2f0e82159c3e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
